export const TRENDS_OVERVIEW_COPY = {
  en: {
    title: 'Trends overview',
    subtitle: 'Your glucose patterns, one day at a time.',
    range: 'Period',
    days: 'days',
    loading: 'Loading the selected period and its matched comparison…',
    failed: 'The Trends data could not be loaded.',
    retry: 'Try again',
    coverage: 'Data coverage',
    adequateCoverage: 'Duration and coverage support this comparison',
    lowCoverage: 'Low data coverage — interpret with care',
    shortPeriod:
      'Short view — representative GMI, GRI, and comparisons need at least 14 days.',
    samples: 'readings',
    excluded: 'excluded',
    duplicates: 'duplicates removed',
    glucoseRanges: 'Glucose ranges',
    veryLow: 'Very low',
    low: 'Low',
    target: 'In range',
    high: 'High',
    veryHigh: 'Very high',
    targetRange: 'Your target range',
    basedOnReadings: 'Share of recorded glucose readings',
    metrics: 'Key metrics',
    mean: 'Mean glucose',
    gmi: 'GMI',
    cv: 'CV',
    cvNote: 'Glucose variability',
    gri: 'GRI',
    griHypo: 'Low-glucose component',
    griHyper: 'High-glucose component',
    gmiNote: 'GMI comes from CGM data and is not a laboratory A1C.',
    comparison: 'Matched previous period',
    comparisonUnavailable:
      'Deltas are withheld until both equal periods have adequate coverage.',
    comparisonNote:
      'Current minus previous period · percentage-point differences use pp.',
    meanDelta: 'Mean difference',
    targetDelta: 'In-range difference',
    cvDelta: 'CV difference',
    current: 'Selected period',
    previous: 'Previous period',
    investigateLow: 'Investigate low-glucose events in this period',
    dailyTitle: 'Day by day',
    dailySubtitle: 'Tap a day to see its ranges and coverage.',
    dayRange: 'In-range readings',
    noData: 'No glucose readings in this period',
    noDayData: 'No readings for this day',
    partialDay: 'Part of this day falls in the selected period',
    dailyCoverageNote: 'Faded bars have low coverage. Empty bars have no data.',
    evidence: 'About these data',
  },
  he: {
    title: 'סקירת מגמות',
    subtitle: 'התמונה הרחבה של הסוכר, יום אחרי יום.',
    range: 'תקופה',
    days: 'ימים',
    loading: 'טוען את התקופה שנבחרה ואת תקופת ההשוואה…',
    failed: 'לא הצלחנו לטעון את נתוני המגמות.',
    retry: 'ניסיון נוסף',
    coverage: 'כיסוי נתונים',
    adequateCoverage: 'המשך והכיסוי מספיקים להשוואה הזו',
    lowCoverage: 'כיסוי נתונים נמוך — יש לפרש בזהירות',
    shortPeriod: 'זהו מבט קצר — GMI, GRI והשוואה מייצגת דורשים לפחות 14 ימים.',
    samples: 'קריאות',
    excluded: 'הוחרגו',
    duplicates: 'כפילויות הוסרו',
    glucoseRanges: 'טווחי סוכר',
    veryLow: 'נמוך מאוד',
    low: 'נמוך',
    target: 'בטווח',
    high: 'גבוה',
    veryHigh: 'גבוה מאוד',
    targetRange: 'טווח היעד שלך',
    basedOnReadings: 'אחוז מתוך קריאות הסוכר שנמדדו',
    metrics: 'מדדים מרכזיים',
    mean: 'סוכר ממוצע',
    gmi: 'GMI',
    cv: 'CV',
    cvNote: 'מידת השונות בסוכר',
    gri: 'GRI',
    griHypo: 'רכיב סוכר נמוך',
    griHyper: 'רכיב סוכר גבוה',
    gmiNote: 'GMI מחושב מנתוני CGM ואינו בדיקת A1C במעבדה.',
    comparison: 'התקופה הקודמת התואמת',
    comparisonUnavailable:
      'ההפרשים מוסתרים עד שלשתי התקופות השוות יהיה כיסוי מספיק.',
    comparisonNote: 'התקופה הנבחרת פחות הקודמת · pp מציין נקודות אחוז.',
    meanDelta: 'הפרש בממוצע',
    targetDelta: 'הפרש בשיעור הקריאות בטווח',
    cvDelta: 'הפרש ב־CV',
    current: 'התקופה הנבחרת',
    previous: 'התקופה הקודמת',
    investigateLow: 'חקירת אירועי סוכר נמוך בתקופה הזו',
    dailyTitle: 'יום אחרי יום',
    dailySubtitle: 'לחיצה על יום תציג את הטווחים וכיסוי הנתונים שלו.',
    dayRange: 'קריאות בטווח',
    noData: 'אין קריאות סוכר בתקופה הזו',
    noDayData: 'אין קריאות ביום הזה',
    partialDay: 'רק חלק מהיום נכלל בתקופה הנבחרת',
    dailyCoverageNote:
      'עמודות דהויות מציינות כיסוי נמוך. עמודות ריקות מציינות חוסר בנתונים.',
    evidence: 'על הנתונים בתצוגה',
  },
} as const;
