export const DAILY_OVERVIEW_COPY = {
  en: {
    title: 'Daily overview',
    subtitle: 'Your day, at a glance.',
    previous: 'Previous',
    next: 'Next',
    today: 'Today',
    loading: 'Loading this day…',
    failed: 'This day could not be loaded.',
    retry: 'Try again',
    coverage: 'Data coverage',
    readings: 'readings',
    excluded: 'excluded',
    duplicates: 'duplicates removed',
    coverageAdequate: 'Coverage is at least 70% for this day.',
    coverageLow: 'Coverage is below 70% for this day.',
    noGlucose: 'No valid glucose readings are available for this day.',
    ranges: 'Time in range',
    veryLow: 'Very low',
    low: 'Low',
    target: 'In range',
    high: 'High',
    veryHigh: 'Very high',
    basedOnReadings: 'Of valid glucose readings',
    metrics: 'Daily glucose',
    mean: 'Mean',
    minimum: 'Minimum',
    maximum: 'Maximum',
    cv: 'CV',
    variation: 'Glucose variability',
    insulin: 'Insulin',
    total: 'Total',
    basal: 'Basal',
    bolus: 'Bolus',
    insulinUnavailable: 'Insulin data is unavailable for this day.',
    customize: 'Customize view',
    editorTitle: 'Make this day yours',
    editorDescription: 'Choose a look. Move the cards. See it live below.',
    rangeStyle: 'Time in range style',
    ring: 'Ring',
    bar: 'Color bar',
    list: 'Classic',
    reorder: 'Card order',
    reorderHint:
      'Drag a handle or use the arrows. The preview updates as you arrange.',
    live: 'Live preview',
    save: 'Save design',
    saving: 'Saving…',
    cancel: 'Cancel',
    reset: 'Reset design',
    saved: 'Your design is saved.',
    saveFailed:
      'The design could not be saved. Your changes are still here. Try again.',
    sessionOnly: 'Preview only — changes apply to this visit.',
    noData: 'No data',
  },
  he: {
    title: 'מבט יומי',
    subtitle: 'היום שלך, במבט אחד.',
    previous: 'הקודם',
    next: 'הבא',
    today: 'היום',
    loading: 'טוען את היום…',
    failed: 'לא הצלחנו לטעון את היום הזה.',
    retry: 'ניסיון נוסף',
    coverage: 'כיסוי נתונים',
    readings: 'קריאות',
    excluded: 'הוחרגו',
    duplicates: 'כפילויות הוסרו',
    coverageAdequate: 'הכיסוי ביום הזה הוא לפחות 70%.',
    coverageLow: 'הכיסוי ביום הזה נמוך מ־70%.',
    noGlucose: 'אין קריאות סוכר תקינות זמינות ליום הזה.',
    ranges: 'זמן בטווח',
    veryLow: 'נמוך מאוד',
    low: 'נמוך',
    target: 'בטווח',
    high: 'גבוה',
    veryHigh: 'גבוה מאוד',
    basedOnReadings: 'מתוך קריאות הסוכר התקינות',
    metrics: 'סוכר יומי',
    mean: 'ממוצע',
    minimum: 'מינימום',
    maximum: 'מקסימום',
    cv: 'CV',
    variation: 'שונות הסוכר',
    insulin: 'אינסולין',
    total: 'סה״כ',
    basal: 'בזאל',
    bolus: 'בולוס',
    insulinUnavailable: 'נתוני אינסולין אינם זמינים ליום זה.',
    customize: 'עיצוב התצוגה',
    editorTitle: 'המבט היומי, בדרך שלך',
    editorDescription: 'בוחרים סגנון, מסדרים כרטיסים ורואים את השינוי מיד.',
    rangeStyle: 'איך להציג זמן בטווח?',
    ring: 'טבעת',
    bar: 'פס צבעוני',
    list: 'קלאסי',
    reorder: 'סדר הכרטיסים',
    reorderHint: 'גוררים מהידית או משתמשים בחיצים. התצוגה מתעדכנת עם הסידור.',
    live: 'תצוגה חיה',
    save: 'שמירת העיצוב',
    saving: 'שומר…',
    cancel: 'ביטול',
    reset: 'איפוס העיצוב',
    saved: 'העיצוב שלך נשמר.',
    saveFailed: 'לא הצלחנו לשמור. השינויים שלך עדיין כאן. אפשר לנסות שוב.',
    sessionOnly: 'תצוגה מקדימה — השינויים חלים בביקור הזה בלבד.',
    noData: 'אין נתונים',
  },
} as const;
