export const DAILY_OVERVIEW_COPY = {
  en: {
    title: 'Daily overview',
    subtitle: 'Your day, at a glance.',
    previous: 'Previous',
    next: 'Next',
    today: 'Today',
    loading: 'Loading this day…',
    failed: 'This day could not be loaded.',
    retry: 'Try again',
    coverage: 'Data coverage',
    readings: 'readings',
    excluded: 'excluded',
    duplicates: 'duplicates removed',
    coverageAdequate: 'Coverage is at least 70% for this day.',
    coverageLow: 'Coverage is below 70% for this day.',
    noGlucose: 'No valid glucose readings are available for this day.',
    ranges: 'Time in range',
    veryLow: 'Very low',
    low: 'Low',
    target: 'In range',
    high: 'High',
    veryHigh: 'Very high',
    basedOnReadings: 'Of valid glucose readings',
    targetRange: 'Target range',
    rangeDetails: 'Range details',
    hideRangeDetails: 'Hide range details',
    rangeCoverage: 'of the day covered',
    rangeCoverageSoFar: 'of today so far covered',
    daySoFar: 'Today so far',
    asOf: 'As of',
    estimated: 'Estimated',
    insulinSplit: 'Basal / bolus',
    insulinEstimateNote:
      'Basal is estimated from the schedule and temporary rates.',
    insulinCompare: 'Compared with',
    yesterday: 'Previous day',
    weekAverage: '7-day average',
    comparisonDay: 'Selected day',
    comparisonSameTime: 'Each day up to the same time',
    comparisonFullDays: 'Complete days · same daily window',
    comparisonLoading: 'Loading insulin history…',
    comparisonUnavailable:
      'Insulin history is unavailable for this comparison.',
    weekComplete: 'Average of the previous 7 days · all 7 available',
    comparisonChange: 'Change',
    noRatio: 'No ratio when total insulin is zero',
    metrics: 'Daily glucose',
    mean: 'Mean',
    minimum: 'Minimum',
    maximum: 'Maximum',
    cv: 'CV',
    variation: 'Glucose variability',
    insulin: 'Insulin',
    total: 'Total',
    basal: 'Basal',
    bolus: 'Bolus',
    insulinUnavailable: 'Insulin data is unavailable for this day.',
    customize: 'Customize view',
    editorTitle: 'Make this day yours',
    editorDescription: 'Choose a look. Move the cards. See it live below.',
    rangeStyle: 'Time in range style',
    ring: 'Ring',
    bar: 'Color bar',
    list: 'Classic',
    reorder: 'Card order',
    reorderHint:
      'Drag a handle or use the arrows. The preview updates as you arrange.',
    live: 'Live preview',
    save: 'Save design',
    saving: 'Saving…',
    cancel: 'Cancel',
    reset: 'Reset design',
    saved: 'Your design is saved.',
    saveFailed:
      'The design could not be saved. Your changes are still here. Try again.',
    sessionOnly: 'Preview only — changes apply to this visit.',
    noData: 'No data',
  },
  he: {
    title: 'מבט יומי',
    subtitle: 'היום שלך, במבט אחד.',
    previous: 'הקודם',
    next: 'הבא',
    today: 'היום',
    loading: 'טוען את היום…',
    failed: 'לא הצלחנו לטעון את היום הזה.',
    retry: 'ניסיון נוסף',
    coverage: 'כיסוי נתונים',
    readings: 'קריאות',
    excluded: 'הוחרגו',
    duplicates: 'כפילויות הוסרו',
    coverageAdequate: 'הכיסוי ביום הזה הוא לפחות 70%.',
    coverageLow: 'הכיסוי ביום הזה נמוך מ־70%.',
    noGlucose: 'אין קריאות סוכר תקינות זמינות ליום הזה.',
    ranges: 'זמן בטווח',
    veryLow: 'נמוך מאוד',
    low: 'נמוך',
    target: 'בטווח',
    high: 'גבוה',
    veryHigh: 'גבוה מאוד',
    basedOnReadings: 'מתוך קריאות הסוכר התקינות',
    targetRange: 'טווח היעד',
    rangeDetails: 'פירוט הטווחים',
    hideRangeDetails: 'הסתרת הפירוט',
    rangeCoverage: 'מהיום עם נתונים',
    rangeCoverageSoFar: 'מהיום עד עכשיו עם נתונים',
    daySoFar: 'היום עד עכשיו',
    asOf: 'עד',
    estimated: 'הערכה',
    insulinSplit: 'בזאל / בולוס',
    insulinEstimateNote: 'הבזאל הוא הערכה לפי התוכנית והקצבים הזמניים.',
    insulinCompare: 'בהשוואה ל־',
    yesterday: 'היום הקודם',
    weekAverage: 'ממוצע 7 ימים',
    comparisonDay: 'היום הנבחר',
    comparisonSameTime: 'בכל יום עד אותה שעה',
    comparisonFullDays: 'ימים מלאים · אותו חלון יומי',
    comparisonLoading: 'טוען היסטוריית אינסולין…',
    comparisonUnavailable: 'אין נתוני אינסולין זמינים להשוואה הזאת.',
    weekComplete: 'ממוצע 7 הימים הקודמים · כל 7 הימים זמינים',
    comparisonChange: 'שינוי',
    noRatio: 'אין יחס כשסך האינסולין הוא אפס',
    metrics: 'סוכר יומי',
    mean: 'ממוצע',
    minimum: 'מינימום',
    maximum: 'מקסימום',
    cv: 'CV',
    variation: 'שונות הסוכר',
    insulin: 'אינסולין',
    total: 'סה״כ',
    basal: 'בזאל',
    bolus: 'בולוס',
    insulinUnavailable: 'נתוני אינסולין אינם זמינים ליום זה.',
    customize: 'עיצוב התצוגה',
    editorTitle: 'המבט היומי, בדרך שלך',
    editorDescription: 'בוחרים סגנון, מסדרים כרטיסים ורואים את השינוי מיד.',
    rangeStyle: 'איך להציג זמן בטווח?',
    ring: 'טבעת',
    bar: 'פס צבעוני',
    list: 'קלאסי',
    reorder: 'סדר הכרטיסים',
    reorderHint: 'גוררים מהידית או משתמשים בחיצים. התצוגה מתעדכנת עם הסידור.',
    live: 'תצוגה חיה',
    save: 'שמירת העיצוב',
    saving: 'שומר…',
    cancel: 'ביטול',
    reset: 'איפוס העיצוב',
    saved: 'העיצוב שלך נשמר.',
    saveFailed: 'לא הצלחנו לשמור. השינויים שלך עדיין כאן. אפשר לנסות שוב.',
    sessionOnly: 'תצוגה מקדימה — השינויים חלים בביקור הזה בלבד.',
    noData: 'אין נתונים',
  },
} as const;
