import {StyleSheet} from 'react-native';

export const dailyOverviewCardStyles = StyleSheet.create({
  row: {flexDirection: 'row', alignItems: 'center', gap: 8},
  reverse: {flexDirection: 'row-reverse'},
  rtlText: {textAlign: 'right', writingDirection: 'rtl'},
  alignRight: {textAlign: 'right'},
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E1E9EE',
    padding: 18,
  },
  darkCard: {backgroundColor: '#111D2D', borderColor: '#34445B'},
  lightText: {color: '#F3F7FF'},
  darkFootnote: {color: '#A6B7CC'},
  darkWarning: {color: '#F4C276'},
  title: {fontSize: 17, fontWeight: '700', color: '#233D49', flex: 1},
  small: {fontSize: 12, color: '#647785'},
  tag: {
    fontSize: 11,
    color: '#68DFC7',
    backgroundColor: '#203B3D',
    borderRadius: 7,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontWeight: '800',
  },
  green: {color: '#138266'},
  blue: {color: '#225F8C'},
  rangeHero: {justifyContent: 'center', gap: 16, paddingVertical: 8},
  ring: {width: 136, height: 136},
  ringCenter: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  ringValue: {
    fontSize: 38,
    fontWeight: '800',
    color: '#68DFC7',
    fontVariant: ['tabular-nums'],
    writingDirection: 'ltr',
  },
  greenLabel: {fontSize: 12, color: '#D7E3F3', marginTop: 2},
  rangeExplanation: {flex: 1, minWidth: 64},
  rangeTarget: {
    fontSize: 22,
    fontWeight: '700',
    color: '#F3F7FF',
    writingDirection: 'ltr',
  },
  rangeEyebrow: {fontSize: 11, color: '#A6B7CC', marginVertical: 3},
  rangeCoverageBadge: {
    marginTop: 12,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: '#1B2A3E',
  },
  rangeCoverageValue: {
    fontSize: 19,
    fontWeight: '700',
    color: '#D7E3F3',
    writingDirection: 'ltr',
  },
  rangeNote: {fontSize: 10, color: '#A6B7CC', lineHeight: 15, marginTop: 2},
  rangeSummary: {gap: 6, marginTop: 8},
  rangeSummaryCell: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#1B2A3E',
  },
  rangeSummaryPercent: {
    fontSize: 20,
    fontWeight: '800',
    writingDirection: 'ltr',
    fontVariant: ['tabular-nums'],
  },
  rangeSummaryLabel: {fontSize: 10, color: '#D7E3F3', marginTop: 2},
  rangeDetailsButton: {
    minHeight: 40,
    justifyContent: 'space-between',
    paddingTop: 4,
  },
  rangeDetailsText: {fontSize: 11, color: '#A6B7CC'},
  heroPercent: {
    fontSize: 52,
    fontWeight: '800',
    color: '#68DFC7',
    writingDirection: 'ltr',
  },
  rangeBar: {
    flexDirection: 'row',
    height: 18,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#E6EEEB',
    marginVertical: 10,
  },
  rangeSegment: {height: '100%'},
  miniBar: {width: 48, height: 12, marginVertical: 0},
  miniList: {width: 38, gap: 4},
  miniListRow: {flexDirection: 'row', alignItems: 'center', gap: 5},
  miniLine: {height: 3, backgroundColor: '#A7B7C2', flex: 1, borderRadius: 2},
  legend: {marginTop: 8, gap: 4},
  legendRow: {
    minHeight: 34,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 9,
  },
  targetLegendRow: {backgroundColor: '#203B3D'},
  dot: {width: 8, height: 8, borderRadius: 4},
  legendLabel: {flex: 1, color: '#D7E3F3', fontSize: 12},
  threshold: {fontSize: 10, color: '#A6B7CC', writingDirection: 'ltr'},
  legendValue: {
    width: 60,
    textAlign: 'right',
    color: '#F3F7FF',
    fontSize: 14,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
    writingDirection: 'ltr',
  },
  footnote: {fontSize: 10, color: '#73858C', marginTop: 7},
  noData: {color: '#647785', lineHeight: 21, marginTop: 12},
  emptyRange: {minHeight: 150, justifyContent: 'center'},
  emptyRangeValue: {fontSize: 48, color: '#A6B7CC', textAlign: 'center'},
  meanCard: {backgroundColor: '#EEF5FC', borderColor: '#D8E7F5'},
  meanValue: {
    fontSize: 30,
    fontWeight: '800',
    marginVertical: 8,
    writingDirection: 'ltr',
    fontVariant: ['tabular-nums'],
  },
  statsRow: {marginTop: 16, alignItems: 'stretch'},
  stat: {flex: 1, minWidth: 0, gap: 4},
  statValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#233D49',
    writingDirection: 'ltr',
    fontVariant: ['tabular-nums'],
  },
  coverageCard: {backgroundColor: '#F2F7F5', borderColor: '#DFEAE4'},
  coverageValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#426C5D',
    writingDirection: 'ltr',
  },
  coverageTrack: {
    height: 5,
    backgroundColor: '#DAE6DF',
    borderRadius: 3,
    marginVertical: 14,
    overflow: 'hidden',
  },
  coverageFill: {height: '100%', borderRadius: 3},
  coverageAdequateFill: {backgroundColor: '#448A78'},
  coverageLowFill: {backgroundColor: '#A96B25'},
  coverageMessage: {
    fontSize: 12,
    lineHeight: 19,
    color: '#426C5D',
    marginTop: 10,
  },
  warning: {color: '#925615'},
  compact: {gap: 10},
  compactValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#344F62',
    writingDirection: 'ltr',
    flexShrink: 1,
  },
});
