export const HOME_COPY = {
  he: {
    title: 'הבית שלי',
    subtitle: 'התמונה שלך, בדרך שלך.',
    tools: 'כל הכלים',
    personal: 'הבית שלי',
    edit: 'עיצוב הבית',
    refresh: 'רענון',
    editor: 'בונים את הבית שלך',
    description: 'בחרו מה חשוב לכם, גררו לסדר הרצוי וראו את התוצאה תוך כדי.',
    widgets: 'מה להציג בבית?',
    order: 'הסדר שלכם',
    preview: 'תצוגה חיה',
    previewHint:
      'כך ייראה הבית שלכם. הנתונים אמיתיים, השינויים נשמרים רק בלחיצה על שמירה.',
    save: 'שמירת הבית',
    saving: 'שומר…',
    saved: 'הבית נשמר',
    cancel: 'ביטול',
    reset: 'איפוס העיצוב',
    saveError: 'השמירה לא הצליחה. העיצוב נשאר כאן, אפשר לנסות שוב.',
    defaultView: 'כשנכנסים הביתה',
    window: 'טווח גרף הסוכר',
    hours6: '6 שעות',
    hours12: '12 שעות',
    fullDay: 'היום כולו',
    empty: 'הבית מחכה לבחירה שלכם',
    emptyHint: 'הוסיפו כרטיסים דרך ״עיצוב הבית״.',
    loading: 'טוען נתונים…',
    unavailable: 'הנתונים אינם זמינים כרגע',
    error: 'לא הצלחנו לטעון את הנתונים',
    refreshing: 'מעדכן…',
    refreshFailed: 'העדכון לא הצליח. מוצגים הנתונים מהטעינה הקודמת.',
    noGlucose: 'אין קריאות סוכר בטווח הזה',
    today: 'היום',
    coverage: 'כיסוי קריאות עד שעת העדכון',
    lastReading: 'קריאה אחרונה',
    minutesAgo: 'דקות מאז הקריאה',
    to: 'עד',
    dailyInsulin: 'אינסולין יומי',
    basal: 'בזאל',
    bolus: 'בולוס',
    total: 'סה״כ',
    week: '7 הימים המלאים האחרונים',
    mean: 'ממוצע סוכר',
    daysAvailable: 'ימים עם נתונים',
    partial: 'עמודה בהירה: פחות מ־70% כיסוי. — מציין נתון חסר.',
    insulinNote:
      'יום חסר אינו נספר כאפס. בזאל ובולוס מוצגים לפי הנתונים הזמינים.',
    range: 'זמן בטווח',
    rangeNote: 'אחוז הקריאות בטווח היעד',
    open: 'פתיחת הפירוט',
    chat: 'מקום לשאלה שלך',
    chatHint:
      'פתחו את הצ׳אט כדי לשאול על הנתונים, לזהות דפוסים ולהעמיק במה שמעניין אתכם.',
    chatOpen: 'פתיחת צ׳אט',
    chatUnavailable: 'אפשר לפתוח את הצ׳אט ולהשלים את ההגדרה.',
    labels: {
      'glucose-graph': 'גרף סוכר',
      'time-in-range': 'זמן בטווח',
      'daily-insulin': 'אינסולין יומי',
      'weekly-glucose': 'מגמת סוכר שבועית',
      'weekly-insulin': 'מגמת אינסולין שבועית',
      chat: 'צ׳אט',
    },
    hints: {
      'glucose-graph': 'הסוכר לאורך היום',
      'time-in-range': 'התפלגות הקריאות היום',
      'daily-insulin': 'בזאל ובולוס מהיום',
      'weekly-glucose': 'ממוצע יומי בשבוע האחרון',
      'weekly-insulin': 'בזאל ובולוס בכל יום',
      chat: 'שיחה במרחק נגיעה',
    },
  },
  en: {
    title: 'My home',
    subtitle: 'Your day, your way.',
    tools: 'All tools',
    personal: 'My home',
    edit: 'Design home',
    refresh: 'Refresh',
    editor: 'Build your home',
    description:
      'Choose what matters, drag to arrange, and see your changes as you go.',
    widgets: 'What goes on your home?',
    order: 'Your order',
    preview: 'Live preview',
    previewHint:
      'This is your home with real data. Changes apply only after saving.',
    save: 'Save home',
    saving: 'Saving…',
    saved: 'Home saved',
    cancel: 'Cancel',
    reset: 'Reset design',
    saveError: 'Could not save. Your design is still here; please try again.',
    defaultView: 'When opening home',
    window: 'Glucose chart window',
    hours6: '6 hours',
    hours12: '12 hours',
    fullDay: 'Full day',
    empty: 'Make this space yours',
    emptyHint: 'Add cards using “Design home”.',
    loading: 'Loading data…',
    unavailable: 'Data is currently unavailable',
    error: 'Could not load the data',
    refreshing: 'Refreshing…',
    refreshFailed: 'Refresh failed. Showing data from the previous load.',
    noGlucose: 'No glucose readings in this window',
    today: 'Today',
    coverage: 'Reading coverage up to the update time',
    lastReading: 'Last reading',
    minutesAgo: 'minutes since reading',
    to: 'through',
    dailyInsulin: 'Daily insulin',
    basal: 'Basal',
    bolus: 'Bolus',
    total: 'Total',
    week: 'Last 7 complete days',
    mean: 'Mean glucose',
    daysAvailable: 'days with data',
    partial: 'Lighter bars: below 70% coverage. — means missing data.',
    insulinNote:
      'Missing days do not count as zero. Basal and bolus reflect available data.',
    range: 'Time in range',
    rangeNote: 'Percentage of readings in your target range',
    open: 'Open details',
    chat: 'A space for your questions',
    chatHint:
      'Open chat to ask about your data, explore patterns, and look closer at what matters to you.',
    chatOpen: 'Open chat',
    chatUnavailable: 'Open chat to complete setup.',
    labels: {
      'glucose-graph': 'Glucose chart',
      'time-in-range': 'Time in range',
      'daily-insulin': 'Daily insulin',
      'weekly-glucose': 'Weekly glucose trend',
      'weekly-insulin': 'Weekly insulin trend',
      chat: 'Chat',
    },
    hints: {
      'glucose-graph': 'Glucose throughout your day',
      'time-in-range': 'Today’s reading distribution',
      'daily-insulin': 'Today’s basal and bolus',
      'weekly-glucose': 'Daily means from the past week',
      'weekly-insulin': 'Basal and bolus each day',
      chat: 'A conversation, one tap away',
    },
  },
} as const;
